# ==================
# Project Details
# ==================
name: 'cdo_analytics'
version: '1.0.0'

# dbt Cloud CLI 
dbt-cloud:
    project-id: 286339

config-version: 2
profile: 'cdo_redshift'
require-dbt-version: [">=1.0.0", "<2.0.0"]
quoting:
  identifier: true
  schema: true

# ==================
# File Path Configs
# ==================
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

# ==================
# Variable Configs
# ==================
vars:
  infinity_future: TO_DATE('9999-12-31', 'YYYY-MM-DD')
  infinity_past: TO_DATE('1970-01-01', 'YYYY-MM-DD')
  tomorrow: DATEADD('day',1,CURRENT_DATE())
  sample_base: base_schema_name__object
  sample_stg: stg_schema_name__object

  # ==================
  # Redshift vars
  # ==================
  valid_at: '{{ run_started_at.strftime("%Y-%m-%d %H:%M:%S%z") }}'

# ==================
# Model Configs 
# https://docs.getdbt.com/docs/configuring-models
# ==================
models:
  # +database: "{{ env_var('DBT_DATABASE')}}"
  # +schema: "{{ env_var('DBT_DB_SCHEMA')}}"
  
  cdo_analytics:
    # applies to all models 
  
    post-hook:
      - "grant select on {{ this }} to group reader_pii_dbt"
      # - "grant select on {{ this }} to group trevorio"
  
    # +grants:
    #   select: ['dbt','trevorio']
  
    +query_tag: dbt
    bind: false

    intermediate:
      tags:
        - "int"
      +materialized: table
      +docs:
        show: false

    marts: 
      tags:
        - "mart"
      +materialized: table

    staging:
      tags:
        - "staging"
      +materialized: view
      +docs:
        show: false
      
      dashboard:
        base: 
          tags:
            - "base" 
          materialized: ephemeral

      dashboard_pii:
        tags:
          - "contains_pii"
        base: 
          tags:
            - "base"
          materialized: ephemeral
      
      legacy_pii:
        tags:
          - "contains_pii"
      
      pegasus_pii:
        tags:
          - "contains_pii"
        base: 
          tags:
            - "base"
          materialized: ephemeral
        +docs:
          show: false

      amplitude:
        base: 
          tags:
            - "base"
          materialized: ephemeral

seeds:
  +docs:
    show: false

