name: Generate DBT Docs

on:
  pull_request:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dbt
        run: python -m pip install dbt-core dbt-redshift

      - name: Set up dbt profile
        env:
          DBT_HOST: ${{ secrets.DBT_HOST }}
        run: |
          mkdir -p ~/.dbt
          echo "
          cdo_redshift:
            target: dev
            outputs:
              dev:
                type: redshift
                host: \"$DBT_HOST\"
                user: \"${{ secrets.DBT_USER_TEST }}\"
                password: \"${{ secrets.DBT_PASSWORD }}\"
                port: 5439
                dbname: dev
                schema: \"${{ secrets.DBT_DB_SCHEMA }}\"
                sslmode: disable
                threads: 16
          " > ~/.dbt/profiles.yml

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Install dbt dependencies
        working-directory: ./dbt
        run: dbt deps

      - name: Generate dbt docs
        working-directory: ./dbt
        run: dbt docs generate
